https://www.geeksforgeeks.org/microsoft-stock-price-prediction-with-machine-learning/

In [1]:
from datetime import datetime
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import numpy as np
import seaborn as sns

In [4]:
import sys

sys.path.append(r'\Users\jimhu\option_trader\src')
from tradingBot.utils.optionTool import delta_call
from tradingBot.utils.optionTool import delta_put
from tradingBot.utils.optionTool import time_to_maturity_in_year
from tradingBot.utils.dataGetter import get_multiple_option_chains
from tradingBot.utils.dataGetter import get_option_exp_date
from tradingBot.utils.dataGetter import get_price_history

from datetime import time, date, datetime, timedelta
from pytz import timezone

from tradingBot.settings.tradeConfig import entryCrit
from tradingBot.settings.tradeConfig import runtimeConfig
from tradingBot.utils.dataGetter import get_price_history
from tradingBot.utils.dataGetter import get_option_exp_date
from tradingBot.consts import asset as at
from tradingBot.excel import positionSheet as ps

In [7]:
symbol = 'SPY'
period = '30y'
interval = '1d'

df = get_price_history(symbol, period=period, interval=interval)

df

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Date,,,,,,,,
1993-05-25 00:00:00-04:00,25.923192,25.923192,25.869335,25.869335,191800,0.0,0.0,0.0
1993-05-26 00:00:00-04:00,25.941138,26.210423,25.923185,26.192471,102400,0.0,0.0,0.0
1993-05-27 00:00:00-04:00,26.228364,26.228364,26.066793,26.102697,53800,0.0,0.0,0.0
1993-05-28 00:00:00-04:00,26.084753,26.084753,25.851373,25.977039,79100,0.0,0.0,0.0
1993-06-01 00:00:00-04:00,26.066809,26.318142,26.030904,26.228380,28300,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
2023-05-18 00:00:00-04:00,414.899994,419.670013,414.670013,419.230011,97177200,0.0,0.0,0.0
2023-05-19 00:00:00-04:00,420.170013,420.720001,417.350006,418.619995,103679700,0.0,0.0,0.0
2023-05-22 00:00:00-04:00,418.640015,420.390015,417.350006,418.790009,60745400,0.0,0.0,0.0
2023-05-23 00:00:00-04:00,417.079987,418.720001,413.679993,414.089996,86383500,0.0,0.0,0.0
2023-05-24 00:00:00-04:00,412.420013,412.820007,409.880005,411.089996,88801600,0.0,0.0,0.0

In [8]:
symbol = 'MSFT'

calls, puts = get_multiple_option_chains(symbol)

calls

,strike,lastPrice,bid,ask,volume,openInterest,impliedVolatility,exp_date,bidSize,askSize,open,high,low,close,delta,gamma,vega,theta,sigma
0,150.0,130.35,0.0,0.0,2.0,0,0.000010,2023-06-02,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
1,220.0,59.40,0.0,0.0,2.0,0,0.000010,2023-06-02,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
2,230.0,82.65,0.0,0.0,NaN,0,0.000010,2023-06-02,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
3,240.0,75.00,0.0,0.0,2.0,0,0.000010,2023-06-02,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
4,245.0,76.87,0.0,0.0,1.0,0,0.000010,2023-06-02,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,415.0,0.15,0.0,0.0,39.0,0,0.125009,2023-08-18,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
58,420.0,0.14,0.0,0.0,13.0,0,0.125009,2023-08-18,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
59,435.0,0.07,0.0,0.0,60.0,0,0.125009,2023-08-18,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
60,440.0,0.03,0.0,0.0,NaN,0,0.125009,2023-08-18,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
61,445.0,0.05,0.0,0.0,22.0,0,0.125009,2023-08-18,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN

In [9]:
current_price = df['Close'].tail(1)

In [10]:
calls['price'] = (calls['bid'] + calls['ask']) / 2
puts['price'] = (puts['bid'] + puts['ask']) / 2

In [11]:
expected_price = float(current_price.values[0]) - 10

print('expected price', expected_price)

calls['gain'] = calls.apply(lambda x: -x['price'] if x['strike'] > expected_price else 100 * (expected_price-x['strike']-x['price'])/x['price'], axis = 1)

puts['gain'] = puts.apply(lambda x: -x['price'] if expected_price > x['strike']  else 100 * (x['strike'] - expected_price - x['price'])/x['price'], axis = 1)

expected price 401.0899963378906

ZeroDivisionError: float division by zero

In [12]:
calls

,strike,lastPrice,bid,ask,volume,openInterest,impliedVolatility,exp_date,bidSize,askSize,open,high,low,close,delta,gamma,vega,theta,sigma,price
0,150.0,130.35,0.0,0.0,2.0,0,0.000010,2023-06-02,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0
1,220.0,59.40,0.0,0.0,2.0,0,0.000010,2023-06-02,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0
2,230.0,82.65,0.0,0.0,NaN,0,0.000010,2023-06-02,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0
3,240.0,75.00,0.0,0.0,2.0,0,0.000010,2023-06-02,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0
4,245.0,76.87,0.0,0.0,1.0,0,0.000010,2023-06-02,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,415.0,0.15,0.0,0.0,39.0,0,0.125009,2023-08-18,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0
58,420.0,0.14,0.0,0.0,13.0,0,0.125009,2023-08-18,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0
59,435.0,0.07,0.0,0.0,60.0,0,0.125009,2023-08-18,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0
60,440.0,0.03,0.0,0.0,NaN,0,0.125009,2023-08-18,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0
61,445.0,0.05,0.0,0.0,22.0,0,0.125009,2023-08-18,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.0

In [ ]:
puts

In [ ]:
calls['lastTradeDate'].strftime("%Y-%m-%d")

In [ ]:
#calls['Exp'] = calls.apply(lambda x: x['lastTradeDate'].strftime("%Y-%m-%d"), axis = 1)
calls['Exp'] = calls.apply(lambda x: x['lastTradeDate'].date(), axis = 1)

In [ ]:
type(calls['Exp'][0])

In [ ]:
q = yf.Ticker(symbol)

q.option_chain()

In [ ]:
exp_date_list = get_option_exp_date(symbol)